carts:
  name: carts
  replicaCount: 1
  image:
    repository: weaveworksdemos/carts
    tag: 0.4.8
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"
  service:
    port: 80
    targetPort: 80
  initContainers:
    - name: wait-for-cartsdb
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z carts-db 27017; do echo waiting for cartsdb; sleep 2; done;",
        ]

cartsDb:
  name: carts-db
  replicaCount: 1
  image:
    repository: mongo
    tag: "3.4"
  service:
    port: 27017
    targetPort: 27017

catalogue:
  name: catalogue
  replicaCount: 1
  image:
    repository: weaveworksdemos/catalogue
    tag: 0.3.5
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  service:
    port: 80
    targetPort: 80
  probe:
    liveness:
      path: /health
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      path: /health
      initialDelaySeconds: 180
      periodSeconds: 3
  initContainers:
    - name: wait-for-cataloguedb
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z catalogue-db 3306; do echo waiting for cataloguedb; sleep 2; done;",
        ]

catalogueDb:
  name: catalogue-db
  replicaCount: 1
  image:
    repository: weaveworksdemos/catalogue-db
    tag: 0.3.0
  env:
    mysqlRootPassword: fake_password
    mysqlDatabase: socksdb
  service:
    port: 3306
    targetPort: 3306

frontEnd:
  name: front-end
  replicaCount: 1
  image:
    repository: weaveworksdemos/front-end
    tag: 0.3.12
  resources:
    limits:
      cpu: 300m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 300Mi
  service:
    port: 80
    targetPort: 8079
  probe:
    liveness:
      path: /
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      path: /
      initialDelaySeconds: 30
      periodSeconds: 3
  env:
    sessionRedis: "true"
  initContainers:
    - name: wait-for-carts
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z carts 80; do echo waiting for carts; sleep 2; done;",
        ]
    - name: wait-for-orders
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z orders 80; do echo waiting for orders; sleep 2; done;",
        ]
    - name: wait-for-catalogue
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z catalogue 80; do echo waiting for catalogue; sleep 2; done;",
        ]
    - name: wait-for-user
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z user 80; do echo waiting for user; sleep 2; done;",
        ]
    - name: wait-for-payment
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z payment 80; do echo waiting for payment; sleep 2; done;",
        ]
    - name: wait-for-shipping
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z shipping 80; do echo waiting for shipping; sleep 2; done;",
        ]

ingress:
  enabled: true
  clusterIssuer: http-01-production
  className: external-nginx
  host: prod.sock-shop.cloudns.be

orders:
  name: orders
  replicaCount: 1
  image:
    repository: weaveworksdemos/orders
    tag: 0.4.7
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"
  service:
    port: 80
    targetPort: 80
  initContainers:
    - name: wait-for-ordersdb
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z orders-db 27017; do echo waiting for ordersdb; sleep 2; done;",
        ]

ordersDb:
  name: orders-db
  replicaCount: 1
  image:
    repository: mongo
    tag: "3.4"
  service:
    port: 27017
    targetPort: 27017

payment:
  name: payment
  replicaCount: 1
  image:
    repository: weaveworksdemos/payment
    tag: 0.4.3
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 99m
      memory: 100Mi
  service:
    port: 80
    targetPort: 80
  probe:
    path: /health
    liveness:
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      initialDelaySeconds: 180
      periodSeconds: 3

queueMaster:
  name: queue-master
  replicaCount: 1
  image:
    repository: weaveworksdemos/queue-master
    tag: 0.3.1
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi
  service:
    port: 80
    targetPort: 80
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"

rabbitmq:
  name: rabbitmq
  replicaCount: 1
  image:
    repository: rabbitmq
    tag: 3.6.8-management
  ports:
    management: 15672
    rabbitmq: 5672
  exporter:
    image:
      repository: kbudde/rabbitmq-exporter
      tag: latest
    port: 9090
  service:
    ports:
      rabbitmq: 5672
      exporter: 9090

sessionDb:
  name: session-db
  replicaCount: 1
  image:
    repository: redis
    tag: alpine
  service:
    port: 6379
    targetPort: 6379

shipping:
  name: shipping
  replicaCount: 1
  image:
    repository: weaveworksdemos/shipping
    tag: 0.4.8
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi
  service:
    port: 80
    targetPort: 80
  env:
    zipkin: zipkin.jaeger.svc.cluster.local
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"

user:
  name: user
  replicaCount: 1
  image:
    repository: weaveworksdemos/user
    tag: 0.4.7
  resources:
    limits:
      cpu: 300m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  service:
    port: 80
    targetPort: 80
  env:
    mongo: user-db:27017
  probe:
    path: /health
    liveness:
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      initialDelaySeconds: 180
      periodSeconds: 3
  initContainers:
    - name: wait-for-userdb
      image: busybox
      command:
        [
          "sh",
          "-c",
          "until nc -z user-db 27017; do echo waiting for userdb; sleep 2; done;",
        ]

userDb:
  name: user-db
  replicaCount: 1
  image:
    repository: weaveworksdemos/user-db
    tag: 0.3.0
  service:
    port: 27017
    targetPort: 27017

nodeSelector:
  kubernetes.io/os: linux
