apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '{{ .Values.rabbitmq.service.ports.exporter }}'
  labels:
    name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.rabbitmq.service.ports.rabbitmq }}
      name: rabbitmq
      targetPort: {{ .Values.rabbitmq.service.ports.rabbitmq }}
    - port: {{ .Values.rabbitmq.service.ports.exporter }}
      name: exporter
      targetPort: exporter
      protocol: TCP
  selector:
    name: {{ .Values.rabbitmq.name }}