apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sessionDb.name }}
  labels:
    name: {{ .Values.sessionDb.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.sessionDb.service.port }}
      targetPort: {{ .Values.sessionDb.service.targetPort }}
  selector:
    name: {{ .Values.sessionDb.name }}