apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.rabbitmq.name }}
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: {{ .Values.rabbitmq.name }}
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          ports:
            - containerPort: {{ .Values.rabbitmq.ports.management }}
              name: management
            - containerPort: {{ .Values.rabbitmq.ports.rabbitmq }}
              name: rabbitmq
          securityContext:
            capabilities:
              drop:
                - all
              add:
                - CHOWN
                - SETGID
                - SETUID
                - DAC_OVERRIDE
            readOnlyRootFilesystem: true
        - name: rabbitmq-exporter
          image: "{{ .Values.rabbitmq.exporter.image.repository }}:{{ .Values.rabbitmq.exporter.image.tag }}"
          ports:
            - containerPort: {{ .Values.rabbitmq.exporter.port }}
              name: exporter
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}