rabbitmq:
  name: rabbitmq
  replicaCount: 1
  image:
    repository: rabbitmq
    tag: 3.6.8-management
  ports:
    management: 15672
    rabbitmq: 5672
  exporter:
    image:
      repository: kbudde/rabbitmq-exporter
      tag: latest
    port: 9090
  service:
    ports:
      rabbitmq: 5672
      exporter: 9090

nodeSelector:
  kubernetes.io/os: linux


