apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.catalogue.name }}
  labels:
    name: {{ .Values.catalogue.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.catalogue.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.catalogue.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.catalogue.name }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w10 {{ .Values.catalogue.name }}-db 3306; do sleep 5; done']
      containers:
        - name: {{ .Values.catalogue.name }}
          image: "{{ .Values.catalogue.image.repository }}:{{ .Values.catalogue.image.tag }}"
          command: ["/app"]
          args:
            - -port={{ .Values.catalogue.service.targetPort }}
          resources:
            {{- toYaml .Values.catalogue.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.catalogue.service.targetPort }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: {{ .Values.catalogue.probe.liveness.path }}
              port: {{ .Values.catalogue.service.targetPort }}
            initialDelaySeconds: {{ .Values.catalogue.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.catalogue.probe.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.catalogue.probe.readiness.path }}
              port: {{ .Values.catalogue.service.targetPort }}
            initialDelaySeconds: {{ .Values.catalogue.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.catalogue.probe.readiness.periodSeconds }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}