apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontEnd.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.frontEnd.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.frontEnd.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.frontEnd.name }}
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox
          command:
            - 'sh'
            - '-c'
            - |
              echo "Waiting for dependent services to be ready..."

              # Wait for catalogue service
              until nc -z -v -w10 {{ .Values.catalogue.name }} 80; do
                echo "catalogue service not available yet, sleeping..."
                sleep 5
              done
              echo "catalogue service is available!"
      containers:
        - name: {{ .Values.frontEnd.name }}
          image: "{{ .Values.frontEnd.image.repository }}:{{ .Values.frontEnd.image.tag }}"
          resources:
            {{- toYaml .Values.frontEnd.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.frontEnd.service.targetPort }}
          env:
            - name: SESSION_REDIS
              value: {{ .Values.frontEnd.env.sessionRedis | quote }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: {{ .Values.frontEnd.probe.liveness.path }}
              port: {{ .Values.frontEnd.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontEnd.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontEnd.probe.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontEnd.probe.readiness.path }}
              port: {{ .Values.frontEnd.service.targetPort }}
            initialDelaySeconds: {{ .Values.frontEnd.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontEnd.probe.readiness.periodSeconds }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}