apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shipping.name }}
  labels:
    name: {{ .Values.shipping.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.shipping.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.shipping.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.shipping.name }}
    spec:
      containers:
        - name: {{ .Values.shipping.name }}
          image: "{{ .Values.shipping.image.repository }}:{{ .Values.shipping.image.tag }}"
          env:
            - name: ZIPKIN
              value: {{ .Values.shipping.env.zipkin }}
            - name: JAVA_OPTS
              value: {{ .Values.shipping.env.javaOpts }}
          resources:
            {{- toYaml .Values.shipping.resources | nindent 10 }}
          ports:
            - containerPort: {{ .Values.shipping.service.targetPort }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}