apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.user.name }}
  labels:
    name: {{ .Values.user.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.user.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.user.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.user.name }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - 'sh'
            - '-c'
            - |
              echo "Waiting for MongoDB to be ready..."
              until nc -z -v -w10 {{ .Values.carts.name }}-db 27017; do
                echo "MongoDB not available yet, sleeping..."
                sleep 1
              done
              echo "MongoDB is available!"
      containers:
        - name: {{ .Values.user.name }}
          image: "{{ .Values.user.image.repository }}:{{ .Values.user.image.tag }}"
          resources:
            {{- toYaml .Values.user.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.user.service.targetPort }}
          env:
            - name: mongo
              value: {{ .Values.user.env.mongo }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: {{ .Values.user.probe.path }}
              port: {{ .Values.user.service.targetPort }}
            initialDelaySeconds: {{ .Values.user.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.user.probe.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.user.probe.path }}
              port: {{ .Values.user.service.targetPort }}
            initialDelaySeconds: {{ .Values.user.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.user.probe.readiness.periodSeconds }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}