queueMaster:
  name: queue-master
  replicaCount: 1
  image:
    repository: weaveworksdemos/queue-master
    tag: 0.3.1
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi
  service:
    port: 80
    targetPort: 80
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"

nodeSelector:
  kubernetes.io/os: linux


