shipping:
  name: shipping
  replicaCount: 1
  image:
    repository: weaveworksdemos/shipping
    tag: 0.4.8
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi
  service:
    port: 80
    targetPort: 80
  env:
    zipkin: zipkin.jaeger.svc.cluster.local
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"

nodeSelector:
  kubernetes.io/os: linux


