orders:
  name: orders
  replicaCount: 1
  image:
    repository: weaveworksdemos/orders
    tag: 0.4.7
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 300Mi
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"
  service:
    port: 80
    targetPort: 80

nodeSelector:
  kubernetes.io/os: linux



