catalogue:
  name: catalogue
  replicaCount: 1
  image:
    repository: weaveworksdemos/catalogue
    tag: 0.3.5
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  service:
    port: 80
    targetPort: 80
  probe:
    liveness:
      path: /health
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      path: /health
      initialDelaySeconds: 180
      periodSeconds: 3

nodeSelector:
  kubernetes.io/os: linux